FROM mcr.microsoft.com/dotnet/sdk:7.0 as build-env
WORKDIR /app
COPY . ./
RUN dotnet restore
RUN dotnet test
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0 
COPY --from=build-env /app/out .
EXPOSE 80
ENTRYPOINT ["dotnet", "Gunetberg.Host.dll"]