name: "release"
on:
    workflow_dispatch:
    push:
        branches: [release]

env:
    DOCKER_USER: ${{secrets.DOCKER_USER}}
    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    REPOSITORY_NAME: ${{secrets.REPOSITORY_NAME}}
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Docker login
              run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
            - name: Date retrieval
              id: date
              run: echo "::set-output name=date::$(date +'%Y%m%d%M')"
            - name: Build the Docker image 
              run: docker build . --file Dockerfile.deploy --tag $DOCKER_USER/$REPOSITORY_NAME:${{steps.date.outputs.date}}
            - name: Docker push
              run: docker push $DOCKER_USER/$REPOSITORY_NAME:${{steps.date.outputs.date}}