name: "Gunetberg image"
on:
    push:
        branches: [release]

env:
    DOCKER_USER: ${{secrets.DOCKER_USER}}
    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    REPOSITORY_NAME: ${{secrets.REPOSITORY_NAME}}
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Docker login
              run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
            - name: Build the Docker image 
              run: docker build . --file deploy/Dockerfile --tag $DOCKER_USER/$REPO_NAME:$(date +%s)
            - name: Docker push
              run: docker push $DOCKER_USER/$REPO_NAME:$(date +%s)